### ISSUE TITLE
No release entry for v3.0.0

### ISSUE THREAD

**Issue by threema-donat** [rwf2/multer#61]
It would be good to know what changed in v3.0.0 so that upgrading to the latest version is less uncertain.

**Comment by SergioBenitez** [comment]
Apologies! Will get to it soon-ish. Here are the commits from the last 2.x release to 3.0: https://github.com/rwf2/multer-rs/compare/d30e0833d1ae5748d7a2fb459d9d9b28e8b2ddb8...master.

The most (only?) interesting changes are:

  - upgrading to http 1.0
  - better `Content-Disposition` parsing (https://github.com/rwf2/multer-rs/commit/bca313f36a336494eba2eb6c7cb6cfc03252cb79)

**Comment by SergioBenitez** [comment]
Done.
